### ISSUE TITLE
use touch for quicker action

### ISSUE THREAD

**Issue by mindengineering** [mindhosting/docker-wordpress#1]
https://github.com/mindhosting/docker-wordpress/blob/355baab752d41a5d395106f9a1dd4bb7659a2e45/entrypoint.sh#L28

**Comment by mindhosting** [comment]
Fixed thank you for your suggestion
https://github.com/mindhosting/docker-wordpress/commit/cf9dfec5f0a3b61b55bdf2fb1a346f363bc5342a
